In [21]:
# Imports 
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
import numpy as np
import math

In [22]:
# Assign Data Values - assume 4 data locations
ndata = 4
data = np.zeros((ndata,3))  # x, y, value
data[0,0] = 25.0;  data[0,1] = 50.0;  data[0,2] = -1.3
data[1,0] = 75.0;  data[1,1] = 80.0;  data[1,2] = 2.5
data[2,0] = 10.0;  data[2,1] = 25.0;  data[2,2] = 3.0
data[3,0] = 95.0;  data[3,1] = 15.0;  data[3,2] = -2.7
data

array([[ 25. ,  50. ,  -1.3],
       [ 75. ,  80. ,   2.5],
       [ 10. ,  25. ,   3. ],
       [ 95. ,  15. ,  -2.7]])

In [28]:
# Calculate Symmetric Covariance Array - assuming variogram with spherical structure with range specified
cov = np.zeros((ndata,ndata))
var_range = 100.0
for i in range(0, ndata):
    for j in range(0, ndata):
        distance = math.sqrt(math.pow((data[i,0]-data[j,0]),2) + math.pow((data[i,1]-data[j,1]),2))
        cova = 0.0
        if(distance < var_range):
            hr = distance / var_range
            cova = 1.0 - hr*(1.5 - 0.5*hr*hr)  # spherical structure, no nugget
            cov[i,j] = cova
cov

array([[ 1.        ,  0.2244834 ,  0.57506938,  0.06574285],
       [ 0.2244834 ,  1.        ,  0.03145365,  0.13715671],
       [ 0.57506938,  0.03145365,  1.        ,  0.0296663 ],
       [ 0.06574285,  0.13715671,  0.0296663 ,  1.        ]])

In [33]:
# LU Decomposition using scipy (used tutorial at www.quantstart.com) 
P, L, U = scipy.linalg.lu(cov)
print(L);  print(U)

[[ 1.          0.          0.          0.        ]
 [ 0.2244834   1.          0.          0.        ]
 [ 0.57506938 -0.10282133  1.          0.        ]
 [ 0.06574285  0.12889386  0.00674212  1.        ]]
[[ 1.          0.2244834   0.57506938  0.06574285]
 [ 0.          0.9496072  -0.09763988  0.12239854]
 [ 0.          0.          0.65925575  0.00444478]
 [ 0.          0.          0.          0.97987149]]


In [39]:
# Test the LU Decomposition
Test = cov - np.matmul(L,U)
Test  # should be zeros

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.38777878e-17,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00]])

In [58]:
# Unconditional Realization at the Specified Locations
rand = np.zeros((ndata))
for i in range(0, ndata):
    rand[i] = np.random.normal()
realization = np.matmul(L,rand)
print(realization)

[ 1.84674634  0.90973758  2.40580429  1.60080233]
